### ISSUE TITLE
Can you add theme without system save ? 

### ISSUE THREAD

**Issue by Gamevita** [MRGhidini/Psvimgtools-Easy-FrontEnd#5]
Hello !  Is it possible to add custom themes without needing to back up the system?
cordially.
Byye !!

**Comment by chronoss09** [comment]
Same thing that you...

**Comment by MRGhidini** [comment]
Hello my friend, how are you ?
Question
Hello ! Is it possible to add custom themes without needing to back up the system?
Answer: Unfortunately no, but I explic.
Every time you choose the option thema, the program adds a line inside your database with the chosen thema path.
So the reason is basically this, access the vita database.
And as the idea is for all versions of vita.
For now this is the only one mode
